ENT.Type = "anim"
ENT.PrintName = "bf2142 pod top"
ENT.Nicknames = {"bf2142 pod top"}
ENT.Author = "thelaughingcheese"
ENT.Category = "Battlefield 2142"
ENT.Spawnable = false
ENT.AdminSpawnable = false
ENT.Information	 = "its a pod top"
ENT.Model = "models/odst/pod/drop_pod_cover.mdl"