ITEM.name = "MA-37 ICWS"
ITEM.desc = "Neat!"
ITEM.category = "Halo"
ITEM.model = "models/ishi/halo_rebirth/weapons/unsc/w_ma37.mdl"
ITEM.class = "drc_ma37"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.price = 1660
ITEM.height = 1
ITEM.permit = "admin"
ITEM.flag = 'H'
ITEM.errormessage = "I don't know how to operate an Assault Rifle..."