ITEM.name = "Arrest Batton"
ITEM.desc = "Neat!"
ITEM.category = "Halo"
ITEM.model = "models/weapons/w_stunbaton.mdl"
ITEM.class = "nut_arrestbaton"
ITEM.weaponCategory = "arrestbatton"
ITEM.width = 2
ITEM.price = 1200
ITEM.height = 1
ITEM.permit = "admin"
ITEM.flag = 'B'
ITEM.errormessage = "Biometric ID Failed..."