ITEM.name = "Type-25 GL"
ITEM.desc = "Sharp Tip Include!"
ITEM.category = "Halo"
ITEM.model = "models/vuthakral/halo/weapons/w_bruteshot.mdl"
ITEM.class = "drc_bruteshot"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.price = 3020
ITEM.height = 2
ITEM.permit = "admin"
ITEM.flag = 'q'
ITEM.errormessage = "I don't know how to operate a Bruteshot..."