ITEM.name = "Type-51 Carbine"
ITEM.desc = "A heretic-hit!"
ITEM.category = "Halo"
ITEM.model = "models/carbine.mdl"
ITEM.class = "drc_t51"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.price = 2040
ITEM.height = 1
ITEM.permit = "admin"
ITEM.flag = 'h'
ITEM.errormessage = "I don't know how to operate a Covenant Carbine..."