ITEM.name = "M932 DMR"
ITEM.desc = "Bloom Included!"
ITEM.category = "Halo"
ITEM.model = "models/vuthakral/halo/weapons/w_dmr.mdl"
ITEM.class = "drc_dmr"
ITEM.weaponCategory = "primary"
ITEM.width = 2
ITEM.price = 1760
ITEM.height = 1
ITEM.permit = "admin"
ITEM.flag = 'H'
ITEM.errormessage = "I don't know how to operate a DMR..."