ITEM.name = "M7S Caseless SMG"
ITEM.desc = "Quiet!"
ITEM.category = "Halo"
ITEM.model = "models/vuthakral/halo/weapons/w_m7s.mdl"
ITEM.class = "drc_m7s"
ITEM.weaponCategory = "primary"
ITEM.width = 1
ITEM.price = 1800
ITEM.height = 1
ITEM.permit = "admin"
ITEM.flag = 'H'
ITEM.errormessage = "I don't know how to operate a Submachine Gun..."