ITEM.name = "Simfphys Repair Tool"
ITEM.desc = "Neat!"
ITEM.category = "Halo"
ITEM.model = "models/weapons/w_physics.mdl"
ITEM.class = "weapon_simrepair"
ITEM.weaponCategory = "repairtool"
ITEM.width = 2
ITEM.price = 1380
ITEM.height = 1
ITEM.permit = "admin"