ITEM.name = "Type-25 C"
ITEM.desc = "A Jiralhanae-hit!"
ITEM.category = "Halo"
ITEM.model = "models/vuthakral/halo/weapons/w_spiker.mdl"
ITEM.class = "drc_spiker"
ITEM.weaponCategory = "primary"
ITEM.width = 1
ITEM.price = 1880
ITEM.height = 1
ITEM.permit = "admin"
ITEM.flag = 'h'
ITEM.errormessage = "I don't know how to operate a Spiker..."