ITEM.name = "M739 LMG"
ITEM.desc = "There's not enough of em!"
ITEM.category = "Halo"
ITEM.model = "models/iterum/saw_w.mdl"
ITEM.class = "drc_saw"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.price = 2460
ITEM.height = 1
ITEM.permit = "admin"
ITEM.flag = 'J'
ITEM.errormessage = "I don't know how to operate a SAW..."