ENT.Type = "anim"
ENT.PrintName = "odst pod bay"
ENT.Nicknames = {"odst pod bay"}
ENT.Author = "thelaughingcheese"
ENT.Category = "Halo ODST"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.Information	 = "its a pod bay"
ENT.Model = "models/odst/pod/drop_pod_bay.mdl"
ENT.Pod = nil
ENT.NextRespawn = CurTime()