ITEM.name = "Warthog Scout Model 2 White"
ITEM.spawnsent = "sim_fphys_halo_warthog_scout"
ITEM.desc = "For all your white transportation needs."
ITEM.skin = 1
ITEM.price = 1180
ITEM.color = Color(255,255,255,255)
ITEM.model = "models/valk/halo5/unsc/vehicles/warthog/warthog_troop.mdl"
ITEM.width = 4
ITEM.height = 4