ITEM.name = "Pelican Transport"
ITEM.spawnent = "wac_hc_transpelican"
ITEM.desc = "Deploys a pelican."
ITEM.skin = 1
ITEM.price = 2100
ITEM.model = "models/valk/haloreach/unsc/pelican/pelican.mdl"
ITEM.width = 4
ITEM.height = 4
ITEM.wac = true