ITEM.name = "Pelican Chin-Gun"
ITEM.spawnent = "wac_hc_milpelican"
ITEM.desc = "Deploys a pelican."
ITEM.skin = 1
ITEM.price = 2600
ITEM.model = "models/valk/haloreach/unsc/pelican/pelican.mdl"
ITEM.width = 4
ITEM.height = 4
ITEM.wac = true