list.Add( "NPCUsableWeapons", { class = "drc_plasma_repeater",	title = "Covenant Plasma Repeater" }  )
list.Add( "NPCUsableWeapons", { class = "drc_mauler",	title = "Covenant Mauler" }  )
list.Add( "NPCUsableWeapons", { class = "drc_t33b",	title = "Covenant Fuel Rod" }  )
list.Add( "NPCUsableWeapons", { class = "drc_energysword",	title = "Covenant Energy Sword" }  )
list.Add( "NPCUsableWeapons", { class = "drc_gravityhammer",	title = "Covenant Gravity Hammer" }  )
list.Add( "NPCUsableWeapons", { class = "drc_plasma_rifle_brute",	title = "Covenant Brute Plasma Rifle" }  )
list.Add( "NPCUsableWeapons", { class = "drc_spiker",	title = "Covenant Spiker" }  )
list.Add( "NPCUsableWeapons", { class = "drc_plasma_pistol",	title = "Covenant Plasma Pistol" }  )
list.Add( "NPCUsableWeapons", { class = "drc_plasma_rifle",	title = "Covenant Plasma Rifle" }  )
list.Add( "NPCUsableWeapons", { class = "drc_bruteshot",	title = "Covenant Bruteshot" }  )
list.Add( "NPCUsableWeapons", { class = "drc_needlerifle",	title = "Covenant Needler Rifle" }  )
list.Add( "NPCUsableWeapons", { class = "drc_needler",	title = "Covenant Needler" }  )
list.Add( "NPCUsableWeapons", { class = "drc_t50",	title = "Covenant Concussion Rifle" }  )
list.Add( "NPCUsableWeapons", { class = "drc_t50srs",	title = "Covenant Beamrifle" }  )
list.Add( "NPCUsableWeapons", { class = "drc_t51",	title = "Covenant Carbine" }  )
list.Add( "NPCUsableWeapons", { class = "drc_focusrifle",	title = "Covenant Focus Rifle" }  )
list.Add( "NPCUsableWeapons", { class = "drc_plasma_caster",	title = "Covenant Plasma Caster" }  )
list.Add( "NPCUsableWeapons", { class = "drc_t57b",	title = "Covenant Carbine 2" }  )
list.Add( "NPCUsableWeapons", { class = "drc_t33a",	title = "Covenant Fuelrod 2" }  )
list.Add( "NPCUsableWeapons", { class = "drc_br55",	title = "Battlerifle" }  )
list.Add( "NPCUsableWeapons", { class = "drc_dmr",	title = "DMR" }  )
list.Add( "NPCUsableWeapons", { class = "drc_m45",	title = "Shotgun" }  )
list.Add( "NPCUsableWeapons", { class = "drc_splaser",	title = "Spartan Laser" }  )
list.Add( "NPCUsableWeapons", { class = "drc_m6s",	title = "Socom" }  )
list.Add( "NPCUsableWeapons", { class = "drc_m6g_reach",	title = "Pistol" }  )
list.Add( "NPCUsableWeapons", { class = "drc_m7",	title = "M7 SMG" }  )
list.Add( "NPCUsableWeapons", { class = "drc_m7057",	title = "Flame Thrower" }  )
list.Add( "NPCUsableWeapons", { class = "drc_saw",	title = "SAW" }  )
list.Add( "NPCUsableWeapons", { class = "drc_m7s",	title = "M7 Silenced" }  )
list.Add( "NPCUsableWeapons", { class = "drc_ma37",	title = "Assault Rifle" }  )
list.Add( "NPCUsableWeapons", { class = "drc_spnkr",	title = "Rocket Launcher" }  )
list.Add( "NPCUsableWeapons", { class = "drc_srs99am",	title = "Sniper" }  )