ENT.Base = "nut_flare"
ENT.PrintName = "Light Blue Flare"
ENT.Author = "Black Tea"
ENT.Spawnable = true
ENT.AdminOnly = true
ENT.Category = "NutScript Throwable"
ENT.RenderGroup 		= RENDERGROUP_BOTH
ENT.configLifetime = 150
ENT.configColor = Color( 0, 216, 255 )