ITEM.name = "Koi"
ITEM.model = "models/rena_haloreach/fish_koi.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.cookable = true
ITEM.hungerAmount = 60
ITEM.foodDesc = "Fresh koi from the local waters."
ITEM.mustCooked = true
ITEM.price = 120