ITEM.name = "Tomato Soup"
ITEM.model = "models/consumables/can_soup.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.cookable = true
ITEM.hungerAmount = 50
ITEM.foodDesc = "Tomato Soup!"
ITEM.mustCooked = true
ITEM.price = 280